### ISSUE TITLE
Save / Load

### ISSUE THREAD

**Issue by tapochek97** [109spbu2sem/Project#10]
@PrideBradley @TonyKat 
Немного не понял строчку в [mainBetaVersionTXT.cpp](https://github.com/109spbu2sem/Project/blob/TonyKat/SaveLoad/mainBetaVersionTXT.cpp#L3)

`#include 'Core.h'` - что это за файл?
`CoreBetaVersionTXT.h` - он?

**Comment by TonyKat** [comment]
Да, это он. Забыл переименовать.
